# Generated by Django 2.2.7 on 2020-01-03 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='العنوان :')),
                ('text', models.TextField(max_length=500, verbose_name='الوصف :')),
                ('image', models.ImageField(upload_to='image', verbose_name='الصوره :')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='انشاء فى :')),
                ('update_by', models.DateTimeField(verbose_name='تم التحديث :')),
                ('slug', models.SlugField(verbose_name='Slug :')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auther', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
