# Generated by Django 2.2.7 on 2020-01-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_in',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.TextField(default=1, max_length=100, verbose_name='وصف صغير :'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='انشاء فى :'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='الصوره :'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug :'),
        ),
        migrations.AlterField(
            model_name='post',
            name='update_by',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تم التحديث :'),
        ),
    ]
