# Generated by Django 2.2.7 on 2020-01-04 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200104_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم:')),
                ('email', models.EmailField(max_length=50, verbose_name='الايميل :')),
                ('coment', models.TextField(max_length=500, verbose_name='التعليق :')),
                ('coment_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False, verbose_name='الحاله :')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post')),
            ],
            options={
                'ordering': ('-coment_date',),
            },
        ),
    ]
