# Generated by Django 2.2.7 on 2020-01-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-comment_date',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='coment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='coment_date',
            new_name='comment_date',
        ),
    ]
