# Generated by Django 2.2.7 on 2020-01-06 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user-image', verbose_name='الصوره : ')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='العنوان :')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('who_i', models.TextField(max_length=150, verbose_name='السيره الذاتيه :')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug :')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_profile')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
