# Generated by Django 2.2.7 on 2020-01-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='who_i',
            field=models.TextField(max_length=300, verbose_name='السيره الذاتيه :'),
        ),
    ]
